                                                                                                                                                                                                                                                               
Delivered-To: nobody@foo.com
Return-Path: <nobody@foo.com>
MIME-Version: 1.0
In-Reply-To: <nobody@foo.com>
References: <nobody@foo.com>
Date: Thu, 15 Oct 2009 11:40:48 +0200
Subject: Re: multipart-alternative message
To: Test <nobody@foo.com>
From: =?ISO-8859-1?Q?Pe=F1a?= <nobody@foo.com>
Content-Type: multipart/alternative; boundary=000e0cd1fd7203f7ae0475f6134e

--000e0cd1fd7203f7ae0475f6134e
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Thanks a lot! I will give it a shot tonight.

Cheers,
Donald




On Thu, Oct 15, 2009 at 11:35 AM, Manolo Pe=F1a <
nobody@foo.com> wrote:

> This is the project I told you.
>
> Regards
> Manolo
>

--000e0cd1fd7203f7ae0475f6134e
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<html>
<head>
</head>
<body>
 <script language="whatever">
  var whatever = 1;
 </script>
 <style>
 .aClass{}
 </style>
Thanks a lot! I will give it a shot tonight.<br><br><br><br>=
Cheers,<br>Donald<br><br><br><br><br><div class=3D"gmail_quote">On Thu, Oc=
t 15, 2009 at 11:35 AM, Pe=F1a <span dir=3D"ltr">&lt;<a h=
nobody@foo.com</a>&=
gt;</span> wrote:<br>
<blockquote class=3D"gmail_quote" style=3D"border-left: 1px solid rgb(204, =
204, 204); margin: 0pt 0pt 0pt 0.8ex; padding-left: 1ex;">This is the proje=
ct =A0I told you in the wiki<br>
<br>
Regards<br>
Manolo<br>

Web Page: <a href="http://code.google.com/intl/es/webtoolkit/">GWT</a><br/>
Email Address: <a href="mailto:donald@example.com">donald@example.com</a>
</blockquote></div><br>
</body>
 <script language="whatever">
  var whatever = 1;
 </script>
</html>

--000e0cd1fd7203f7ae0475f6134e--
