Delivered-To: nobody@foo.com
MIME-Version: 1.0
Date: Thu, 15 Oct 2009 00:47:18 +0200
Subject: FileUpload
From: <nobody@foo.com>
To: nobody@foo.com
Content-Type: multipart/alternative; boundary=000e0ce0eea8eb6b3b0475ecf175

--000e0ce0eea8eb6b3b0475ecf175
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Hola se=F1or

Tengo dos preguntas. La primera es que haciendo exactamente lo que me ha
dicho, consigu=E9 a arrancar el proyecto pero he tenido un error 500, no se
donde viene porque las clases estan correctas (0 error en los "*.java"). Es=
o
no es el gran problema para mi, llegar=E9 a quitar el error 500 (http) ojal=
a.
Mi segunda pregunta (la mas importante) es donde se ponen los ficheros
cargados en el servidor. Busco a partir del browser windows pero no hay
huella del fichero, solo encuentro el fichero original pero su doble que
deberia estar en alguna parte del lado del servidor, ni puta huella, lo
siento  !!  He buscado en el codigo de la servlet responsable del
cargamiento y no encontr=E9 ningun variable PATH que indicaria donde se pon=
en
los ficheros en el servidor.
Gracias de contestar !

--000e0ce0eea8eb6b3b0475ecf175
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Hola se=F1or <br><br>Tengo dos preguntas. La primera es que haciendo exacta=
mente lo que me ha dicho, consigu=E9 a arrancar el proyecto pero he tenido =
un error 500, no se donde viene porque las clases estan correctas (0 error =
en los &quot;*.java&quot;). Eso no es el gran problema para mi, llegar=E9 a=
 quitar el error 500 (http) ojala.=A0 Mi segunda pregunta (la mas important=
e) es donde se ponen los ficheros cargados en el servidor. Busco a partir d=
el browser windows pero no hay huella del fichero, solo encuentro el ficher=
o original pero su doble que deberia estar en alguna parte del lado del ser=
vidor, ni puta huella, lo siento=A0 !!=A0 He buscado en el codigo de la ser=
vlet responsable del cargamiento y no encontr=E9 ningun variable PATH que i=
ndicaria donde se ponen los ficheros en el servidor.<br>
Gracias de contestar !<br>

--000e0ce0eea8eb6b3b0475ecf175--