MIME-Version: 1.0
Received: by 10.239.187.211 with SMTP id m19mr254638hbh.10.1263556376695; Fri, 
    15 Jan 2010 03:52:56 -0800 (PST)
Date: Fri, 15 Jan 2010 12:52:56 +0100
Message-ID: <a194f7b71001150352s7c4beb02wa7c49d44d0e94b2d@mail.gmail.com>
Subject: Listado de temas a tratar
From: Juan Palomo <juan@palomo.com>
To: =?ISO-8859-1?Q?No=20hay=20ma=F1ana?= <hello@hupa.org>
Content-Type: multipart/mixed; boundary=001485f7c300fc945d047d32a46a
X-Virus-Checked: Checked by ClamAV on apache.org

--001485f7c300fc945d047d32a46a
Content-Type: multipart/alternative; boundary=001485f7c300fc9454047d32a468

--001485f7c300fc9454047d32a468
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable


Mira el documento adjunto.


--=20
Mirai Espa=F1a S.L.
Calle Fuencarral 6, 4=BA
28004, Madrid
Tel. 91 5913500
Fax. 91 4473032
http://www.miraiespana.com/
-
Visit http://www.hotelsearch.com/ !!

--001485f7c300fc9454047d32a468
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

Hola<br>
Mira el documento adjunto.<br>

<span>-- <br>
<a href='http://www.mycompany.com>My Company !!</a>
<br>
</span>

--001485f7c300fc9454047d32a468--
--001485f7c300fc945d047d32a46a
Content-Type: text/plain; charset=ISO-8859-1; name="Tareas.txt"
Content-Disposition: attachment; filename="Latin.txt"
Content-Length: 866
X-Attachment-Id: f_g4gwsd0h0

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
--001485f7c300fc945d047d32a46a--
