Delivered-To: mcdodot@gmail.com
Received: by 10.60.131.212 with SMTP id oo20csp72677oeb;
        Mon, 10 Jun 2013 08:20:07 -0700 (PDT)
X-Received: by 10.205.24.6 with SMTP id rc6mr1584559bkb.141.1370877606962;
        Mon, 10 Jun 2013 08:20:06 -0700 (PDT)
Return-Path: <echowdx@gmail.com>
Received: from mail-bk0-x233.google.com (mail-bk0-x233.google.com [2a00:1450:4008:c01::233])
        by mx.google.com with ESMTPS id kf6si1566340bkb.107.2013.06.10.08.20.06
        for <mcdodot@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Mon, 10 Jun 2013 08:20:06 -0700 (PDT)
Received-SPF: pass (google.com: domain of echowdx@gmail.com designates 2a00:1450:4008:c01::233 as permitted sender) client-ip=2a00:1450:4008:c01::233;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of echowdx@gmail.com designates 2a00:1450:4008:c01::233 as permitted sender) smtp.mail=echowdx@gmail.com;
       dkim=pass header.i=@gmail.com
Received: by mail-bk0-x233.google.com with SMTP id ji1so2631218bkc.24
        for <mcdodot@gmail.com>; Mon, 10 Jun 2013 08:20:06 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=message-id:date:from:user-agent:mime-version:to:subject:references
         :in-reply-to:x-chiaramail-content-pointer
         :x-chiaramail-content-server-name:x-chiaramail-content-server-port
         :content-type:content-transfer-encoding;
        bh=40fimkYYpXaLiVIKuTv2tLgUPaqUGA1DOkoRGdypt/8=;
        b=AzWWH4udXhYp8dNi1IdLVpDKDZVeNA2363k1/NhOHYucX/tPZSBWdpT9tNPBjxDEiV
         O/8nINUhZfC8ClQy4ZPvd/VklvH6jLZG3+uzkUVX5lXDVokWwtz6DhSgb6k7nFwFkNeL
         ImHWZcROVkYbghoGhIvuW/2EElAvOOKCw9mPLuh3jLv2ymFAX3Qo/Gdkq17tGaxdk1Bx
         BrZ4DaAoK1Tnb0CCRNqUWX8UWToYzgXED22PUtSD6FjWHT9hOFBlgWFAdcK6bIOOKHec
         XFuhLrB7bvKUSooMUG3vrWQmgzo8e0uEWyLez1blwYn7maOpuNO4P3937dm4JkE4yxGB
         wSLQ==
X-Received: by 10.204.187.209 with SMTP id cx17mr1609776bkb.143.1370877606450;
        Mon, 10 Jun 2013 08:20:06 -0700 (PDT)
Return-Path: <echowdx@gmail.com>
Received: from [10.20.0.2] ([69.85.95.7])
        by mx.google.com with ESMTPSA id tl1sm4088263bkb.7.2013.06.10.08.20.04
        for <mcdodot@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Mon, 10 Jun 2013 08:20:05 -0700 (PDT)
Message-ID: <51B5EEA0.7040304@gmail.com>
Date: Mon, 10 Jun 2013 23:20:00 +0800
From: dongxu <echowdx@gmail.com>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:17.0) Gecko/20130509 Thunderbird/17.0.6
MIME-Version: 1.0
To: Manuel Carrasco <mcdodot@gmail.com>
Subject: Re: Test 1
References: <51B5EDF3.3080809@gmail.com>
In-Reply-To: <51B5EDF3.3080809@gmail.com>
X-ChiaraMail-Content-Pointer: 8
X-ChiaraMail-Content-Server-Name: www.chiaramail.com
X-ChiaraMail-Content-Server-Port: 443
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

This message was sent using ECS technology 
(http://en.wikipedia.org/wiki/Envelope-content_splitting), but your mail 
client does not support ECS. Please download and install the appropriate 
ECS-enabling software for your mail client 
(http://www.chiaramail.com/download_extension.html) to read this message.
