Delivered-To: mcdodot@gmail.com
Received: by 10.60.131.212 with SMTP id oo20csp73659oeb;
        Mon, 10 Jun 2013 08:49:12 -0700 (PDT)
X-Received: by 10.205.22.196 with SMTP id qx4mr1610488bkb.57.1370879351744;
        Mon, 10 Jun 2013 08:49:11 -0700 (PDT)
Return-Path: <echowdx@gmail.com>
Received: from mail-bk0-x22a.google.com (mail-bk0-x22a.google.com [2a00:1450:4008:c01::22a])
        by mx.google.com with ESMTPS id t2si950481bkh.191.2013.06.10.08.49.11
        for <mcdodot@gmail.com>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Mon, 10 Jun 2013 08:49:11 -0700 (PDT)
Received-SPF: pass (google.com: domain of echowdx@gmail.com designates 2a00:1450:4008:c01::22a as permitted sender) client-ip=2a00:1450:4008:c01::22a;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of echowdx@gmail.com designates 2a00:1450:4008:c01::22a as permitted sender) smtp.mail=echowdx@gmail.com;
       dkim=pass header.i=@gmail.com
Received: by mail-bk0-x22a.google.com with SMTP id jk13so3448363bkc.1
        for <mcdodot@gmail.com>; Mon, 10 Jun 2013 08:49:11 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=message-id:date:from:user-agent:mime-version:to:subject
         :x-chiaramail-content-pointer:x-chiaramail-content-key2
         :x-chiaramail-content-server-name:x-chiaramail-content-server-port
         :content-type:content-transfer-encoding;
        bh=40fimkYYpXaLiVIKuTv2tLgUPaqUGA1DOkoRGdypt/8=;
        b=vvOKuDgFhW7lhslsd+p1zFzCgGsB1q+Nz/VX94yvOzYNgzK+ztjWuRXqhxInvKB/6A
         KULfTqxc6eCGaOwQe2jfzcCnE9NqbqNyqWdrKGtcYo/kC3cmSM+vPiVVwin4Ocib+tZk
         gLRThq7wglPAniM9+y0MEtXWU2C0PRWCKM/keEZloAJrL9x3RR/5vQ3Cn8oVyI5yg328
         sFIUYa2UvKJ+3rb3I/XCoqaDu26+A2wDiemzPMXUP3p3rTawvt/Bmg8SsxuzCo5zi8vf
         oUsbFJWM9wPxCW53BBKQXNJ8yIPh+MD76ymg6bGuKHkSilqfTQk1NCr8QbFdO/FaeAba
         Ad5g==
X-Received: by 10.204.74.138 with SMTP id u10mr1617410bkj.113.1370879351096;
        Mon, 10 Jun 2013 08:49:11 -0700 (PDT)
Return-Path: <echowdx@gmail.com>
Received: from [10.20.0.2] ([69.85.95.7])
        by mx.google.com with ESMTPSA id jm15sm4132474bkb.13.2013.06.10.08.49.08
        for <multiple recipients>
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Mon, 10 Jun 2013 08:49:10 -0700 (PDT)
Message-ID: <51B5F571.1050502@gmail.com>
Date: Mon, 10 Jun 2013 23:49:05 +0800
From: dongxu <echowdx@gmail.com>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:17.0) Gecko/20130509 Thunderbird/17.0.6
MIME-Version: 1.0
To: Manuel Carrasco <mcdodot@gmail.com>
Subject: Test with bcc without content inside
X-ChiaraMail-Content-Pointer: 72
X-ChiaraMail-Content-Key2: 98333074730306711837946622793808
X-ChiaraMail-Content-Server-Name: www.chiaramail.com
X-ChiaraMail-Content-Server-Port: 443
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

This message was sent using ECS technology 
(http://en.wikipedia.org/wiki/Envelope-content_splitting), but your mail 
client does not support ECS. Please download and install the appropriate 
ECS-enabling software for your mail client 
(http://www.chiaramail.com/download_extension.html) to read this message.
