Delivered-To: hupa4ecs@gmail.com
Received: by 10.194.20.5 with SMTP id j5csp57047wje;
        Thu, 15 Aug 2013 23:40:10 -0700 (PDT)
X-Received: by 10.180.188.49 with SMTP id fx17mr4168116wic.49.1376635210470;
        Thu, 15 Aug 2013 23:40:10 -0700 (PDT)
Return-Path: <mcdodot@gmail.com>
Received: from mail-wi0-x236.google.com (mail-wi0-x236.google.com [2a00:1450:400c:c05::236])
        by mx.google.com with ESMTPS id hm1si12839wib.51.1969.12.31.16.00.00
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Thu, 15 Aug 2013 23:40:10 -0700 (PDT)
Received-SPF: pass (google.com: domain of mcdodot@gmail.com designates 2a00:1450:400c:c05::236 as permitted sender) client-ip=2a00:1450:400c:c05::236;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of mcdodot@gmail.com designates 2a00:1450:400c:c05::236 as permitted sender) smtp.mail=mcdodot@gmail.com;
       dkim=pass header.i=@gmail.com;
       dmarc=pass (p=NONE dis=NONE) d=gmail.com
Received: by mail-wi0-x236.google.com with SMTP id hi8so465149wib.9
        for <hupa4ecs@gmail.com>; Thu, 15 Aug 2013 23:40:10 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=message-id:date:from:user-agent:mime-version:to:subject
         :content-type:content-transfer-encoding;
        bh=40fimkYYpXaLiVIKuTv2tLgUPaqUGA1DOkoRGdypt/8=;
        b=mqMNAF+icS8do7uoVHHtaYRrxh7Yh50ZAV3ZXuDQLQIUjf+3spMQn37P2p+xhDsH/3
         fpOiFi5OzF6ufmUTd8kXe5E/jYmO0wxAvzSZ/Rzgif40EVAJ/1XEoW5ISspHL4tIJtwc
         JYCwmCoViYf/O453zXAAAf7HeA63WqkxOnbD2C0MyF4ucOkmW9XJJDnRVn154vt7IIZa
         7ZzXQyQjZ6Huf8fX6iNUM7VR5mPW8NYU5qfho6VmgpagBLGApWKC2CMo8Om9qg1KvQ9s
         n9pbSlgHwUcSZNJt1RE/xSItkEhjM0Imkutr/x5J/Qk/G/Ny+HH5OpjFa1kgB3/K0gND
         eXzQ==
X-Received: by 10.180.72.140 with SMTP id d12mr32810wiv.11.1376635210416;
        Thu, 15 Aug 2013 23:40:10 -0700 (PDT)
Return-Path: <mcdodot@gmail.com>
Received: from [192.168.1.35] (25.Red-88-22-232.staticIP.rima-tde.net. [88.22.232.25])
        by mx.google.com with ESMTPSA id hb2sm937458wib.0.1969.12.31.16.00.00
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Thu, 15 Aug 2013 23:40:09 -0700 (PDT)
Message-ID: <520DC948.50505@gmail.com>
Date: Fri, 16 Aug 2013 08:40:08 +0200
From: Manuel Carrasco <mcdodot@gmail.com>
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:17.0) Gecko/20130803 Thunderbird/17.0.8
MIME-Version: 1.0
To: hupa4ecs@gmail.com
Subject: Encrypted message
X-ChiaraMail-Content-Pointer: 40
X-ChiaraMail-Content-Key2: 02192564530017260336297834796621
X-ChiaraMail-Content-Server-Name: www.chiaramail.com
X-ChiaraMail-Content-Server-Port: 443
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

This message was sent using ECS technology 
(http://en.wikipedia.org/wiki/Envelope-content_splitting), but your mail 
client does not support ECS. Please download and install the appropriate 
ECS-enabling software for your mail client 
(http://www.chiaramail.com/download_extension.html) to read this message.
