Return-Path: <mcdodot@gmail.com>
Received: from [192.168.1.35] (239.Red-79-148-67.dynamicIP.rima-tde.net. [79.148.67.239])
        by mx.google.com with ESMTPSA id l7sm2877195wiw.4.1969.12.31.16.00.00
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Thu, 15 Aug 2013 06:08:16 -0700 (PDT)
Message-ID: <520CD2B7.5090500@gmail.com>
Date: Thu, 15 Aug 2013 15:08:07 +0200
From: Manuel Carrasco <mcdodot@gmail.com>
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:17.0) Gecko/20130803 Thunderbird/17.0.8
MIME-Version: 1.0
To: mcdodot@gmail.com
Subject: ECS unencripted attachment
X-ChiaraMail-Content-Pointer: 16 24
X-ChiaraMail-Content-Server-Name: www.chiaramail.com
X-ChiaraMail-Content-Server-Port: 443
Content-Type: multipart/mixed;
 boundary="------------020706090302030909010608"

This is a multi-part message in MIME format.
--------------020706090302030909010608
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

This message was sent using ECS technology 
(http://en.wikipedia.org/wiki/Envelope-content_splitting), but your mail 
client does not support ECS. Please download and install the appropriate 
ECS-enabling software for your mail client 
(http://www.chiaramail.com/download_extension.html) to read this message.

--------------020706090302030909010608
Content-Type: application/pdf;
 name="TRATAMIENTOS TERMAEUROPA 2013.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="TRATAMIENTOS TERMAEUROPA 2013.pdf"

VGhpcyBtZXNzYWdlIHdhcyBzZW50IHVzaW5nIEVDUyB0ZWNobm9sb2d5IChodHRwOi8vZW4u
d2lraXBlZGlhLm9yZy93aWtpL0VudmVsb3BlLWNvbnRlbnRfc3BsaXR0aW5nKSwgYnV0IHlv
dXIgbWFpbCBjbGllbnQgZG9lcyBub3Qgc3VwcG9ydCBFQ1MuIFBsZWFzZSBkb3dubG9hZCBh
bmQgaW5zdGFsbCB0aGUgYXBwcm9wcmlhdGUgRUNTLWVuYWJsaW5nIHNvZnR3YXJlIGZvciB5
b3VyIG1haWwgY2xpZW50IChodHRwOi8vd3d3LmNoaWFyYW1haWwuY29tL2Rvd25sb2FkX2V4
dGVuc2lvbi5odG1sKSB0byByZWFkIHRoaXMgbWVzc2FnZS4=
--------------020706090302030909010608--
