Delivered-To: hupa4ecs@gmail.com
Received: by 10.194.20.5 with SMTP id j5csp57070wje;
        Thu, 15 Aug 2013 23:41:07 -0700 (PDT)
X-Received: by 10.194.235.138 with SMTP id um10mr21673wjc.30.1376635267019;
        Thu, 15 Aug 2013 23:41:07 -0700 (PDT)
Return-Path: <mcdodot@gmail.com>
Received: from mail-wi0-x235.google.com (mail-wi0-x235.google.com [2a00:1450:400c:c05::235])
        by mx.google.com with ESMTPS id ff5si2193677wic.83.1969.12.31.16.00.00
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Thu, 15 Aug 2013 23:41:07 -0700 (PDT)
Received-SPF: pass (google.com: domain of mcdodot@gmail.com designates 2a00:1450:400c:c05::235 as permitted sender) client-ip=2a00:1450:400c:c05::235;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of mcdodot@gmail.com designates 2a00:1450:400c:c05::235 as permitted sender) smtp.mail=mcdodot@gmail.com;
       dkim=pass header.i=@gmail.com;
       dmarc=pass (p=NONE dis=NONE) d=gmail.com
Received: by mail-wi0-x235.google.com with SMTP id en1so467825wid.8
        for <hupa4ecs@gmail.com>; Thu, 15 Aug 2013 23:41:07 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=message-id:date:from:user-agent:mime-version:to:subject
         :content-type:content-transfer-encoding;
        bh=OiU/cI/pNcRDAxIN/CmIVMY9Lg6v96jdy3UtbyOMeWw=;
        b=FH3VQ+LDscPE/Nk4fm95BbibuXTDDmB4XqgkNqKvp+ruX7GChJQZHuyzc7DxpUT7Je
         8L8d0TBx42JPu+6UdY8pd1bULBz5cnDC/aWeEaWb+rzogRAen1pQIvXAy2bzSBb1fyQY
         E1TZX7oziypusGC5TK6sm1W794h+Jb+zun760vYPqMQLK8MhKQi3uay20g0o8GArgsbV
         BBVjvb1i8DhziXpQ001YRxVUXwJ8/faeq4H1Q3FvaSJ9JxQ6YRmUw/SzIAfryi5TZ8IN
         adI4MgvaXzAW1W1E8oPwCI8fwJQclw5MbFeZHFBpHpG5JDQstd1AmcPHcrcZ7Jnqi2x8
         bufw==
X-Received: by 10.194.104.170 with SMTP id gf10mr53382wjb.90.1376635266968;
        Thu, 15 Aug 2013 23:41:06 -0700 (PDT)
Return-Path: <mcdodot@gmail.com>
Received: from [192.168.1.35] (25.Red-88-22-232.staticIP.rima-tde.net. [88.22.232.25])
        by mx.google.com with ESMTPSA id eb3sm6129872wic.10.1969.12.31.16.00.00
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Thu, 15 Aug 2013 23:41:06 -0700 (PDT)
Message-ID: <520DC980.9030606@gmail.com>
Date: Fri, 16 Aug 2013 08:41:04 +0200
From: Manuel Carrasco <mcdodot@gmail.com>
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:17.0) Gecko/20130803 Thunderbird/17.0.8
MIME-Version: 1.0
To: hupa4ecs@gmail.com
Subject: Include content
X-ChiaraMail-Content-Pointer: 48
X-ChiaraMail-Content-Server-Name: www.chiaramail.com
X-ChiaraMail-Content-Server-Port: 443
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

Hello world included
