Date: Wed, 28 Oct 2009 05:55:26 -0700 (PDT)
From: ® VIAGRA ® Official <nobody@foo.org>
To: tuna@alcala.org
Subject: iso-8859-1 content and headers 
MIME-Version: 1.0
Content-Type: text/html; charset="ISO-8859-1"
Content-Transfer-Encoding: 7bit

<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
      <title>
		News
      </title>
   </head>
   <body>

      <table border="0" cellpadding="0" cellspacing="0" style="width: 896px">


<tr><td align="center" style="font: normal 11px Verdana, sans-serif; color: #333;"><a href="http://mdftfxek.cn" style="text-decoration: none; color: #0099ff;">Click here</a> to view as a web page. </td></tr>

         <tr><td align="center">
        	 <br />
			 <a href="http://mdftfxek.cn">
			 <img alt="View image in browser now" width="618" height="326" src="http://mediapix.ru/pics/4154ded47deaf59b8dad0cc69294fc5b.gif" style="border-width: 0px" /></a></td></tr>


<tr><td valign="top" style="border-right: 1px solid #e5e4e4; padding-right: 10px">
        <table border="0" cellpadding="0" cellspacing="0" style="width: 884px">

<tr><td align="center" style="font: normal 9px Verdana, sans-serif; color: #999; padding-top: 20px">

<a href="http://mdftfxek.cn" style="font: 9px Verdana, sans-serif; text-decoration: none; color: #0099ff">Unsubscribe</a> | 
<a href="http://mdftfxek.cn" style="font: 9px Verdana, sans-serif; text-decoration: none; color: #0099ff">Change e-mail address</a> | 
<a href="http://mdftfxek.cn" style="font: 9px Verdana, sans-serif; text-decoration: none; color: #0099ff">Privacy Policy</a> | 
<a href="http://mdftfxek.cn" style="font: 9px Verdana, sans-serif; text-decoration: none; color: #0099ff">About Us</a><br /><br />
Copyright ® 2009 umew Inc. All rights reserved.<br />
					  </td></tr>

        </table>

</td>
</tr>
      </table>
</body>
</html>


