MIME-Version: 1.0
Content-Type: text/html;
    charset="ISO-8859-1"
Content-Transfer-Encoding: quoted-printable
Date: Tue, 3 Jan 2012 05:03:32 -0800
From: "Voices That Matter" <voicesthatmatter@e.informit.biz>
Reply-To: "Voices That Matter" <voicesthatmatter@informit.com>
Subject: Android Conference - Early Bird Pricing thru January 13
List-Unsubscribe: http://e.pearson.info/pub/optout?_ri_=X0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q44LOKQGQaQvzbf&_ei_=8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6beX6990G11X%3DuHghthxupjHpLkiHgHQJhu
X-sgxh1: uHghthxupjHpLkiHgHQJhu
X-rext: 3.interact2.Wj.EPPW.pkgC.khU.WWewd.E.H.NqM
X-cid: ptg.10897410.149588
To: test@james.apache.org
Message-ID: <0.0.2D.DC4.1CCCA18186668F4.0@om-fen.rsys1.com>

<html>
<head>
<title>Voices That Matter: Android Developers Conference</title>
<meta http-equiv=3D=22Content-Type=22 content=3D=22text/html; charset=3Diso=
-8859-1=22>

<style type=3D=22text/css=22>
<=21--body =7B=20
background-color : =23FFFFFF;=20
width : 100%;
font-family : Arial, Helvetica;=20
=7D -->
</style>
</head>

<body>
<table width=3D=22640=22 border=3D=220=22 cellpadding=3D=226=22 cellspacing=
=3D=224=22 style=3D=22border:1px solid =23999;=22>
<tr>=20
<td><div align=3D=22center=22><a rilt=3D=22AndroidBanner=22 href=3D=22http:=
//e=2Epearson=2Einfo/pub/cc?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q4=
4LOKQGQaQvzbfVXtpKX%3DSRDSCCYC&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6=
BRYqA77GBUCzgCCzgTVGf6beX6990G11X%3DuHghthxupjHpLkiHgHQJhu=2E=22><img src=
=3D=22http://ptgmedia=2Epearsoncmg=2Ecom/imprint_downloads/informit/images/=
conferences/VTMAndroid2012/AndroidHeader640=2Ejpg=22 width=3D=22640=22 heig=
ht=3D=22123=22 alt=3D=22Voices That Matter: Android Developers Conference=
=22 border=3D=220=22 /></a></div></td>
</tr>
<tr>
  <td valign=3D=22top=22 align=3D=22center=22><p><font color=3D=22=2389ac46=
=22 size=3D=225=22><strong>Top Five Reasons to Register Now</strong></font>=
<font size=3D=222=22><br>
    </font></p></td>
</tr>

<tr>
<td width=3D=22635=22 height=3D=22406=22 valign=3D=22top=22>
<p><font size=3D=222=22>5=2E     We have extended our Early Bird pricing for a=
ll of you holiday season procrastinators=2E You can save =24200 by register=
ing before January 13=2E Save even more with the Friends of Pearson Priorit=
y Code=2E Register with this Priority Code =96 <strong>ANDMAL7</strong> =96=
 and save another =24150=2E <a rilt=3D=22vtm_android_register_link1=22 href=
=3D=22http://e=2Epearson=2Einfo/pub/cc?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4=
Qisn8Qso3Q44LOKQGQaQvzbfVXtpKX%3DSRDSCCYD&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qz=
gSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6beX6990G11X%3DuHghthxupjHpLkiHgHQJhu=2E=22=
>Sign up before January 13 and combine the goodness</a>=21
<p>4=2E  Have the chance to meet and hang out with leading authors, and con=
ference chairs, Shane Conder and Lauren Darcey=2E Get your books signed, as=
k questions and propose new ideas=2E Plus, meet the Google folks who are wo=
rking on Android today and every day=2E=20
<p>3=2E  Improve your application development skills with ideas from Eric B=
urke (of Square), Chris Haseman (of Tumblr) and Chirag Mehta (of Amazon)=2E
<p>2=2E  You will be inspired=2E You=92ll have a chance to see how others a=
re leveraging the robust functionality of the Android platform=2E And how o=
thers are marketing their apps=2E You will go back to your office, your fre=
e-lance gig, your own projects with new ideas and new energy=2E <a rilt=3D=
=22vtm_android_register_link2=22 href=3D=22http://e=2Epearson=2Einfo/pub/cc=
?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q44LOKQGQaQvzbfVXtpKX%3DSRDSC=
CYD&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6beX69=
90G11X%3DuHghthxupjHpLkiHgHQJhu=2E=22>Reserve your place today</a>=2E
<p>1=2E  Did we mention special savings?? Combine our Friends of Pearson (<=
strong>ANDMAL7</strong>) discount with Early Bird pricing and you can atten=
d the two-day conference (including breakfast, breaks, lunch and a party) f=
or only =24445=2E <a rilt=3D=22vtm_android_register_link3=22 href=3D=22http=
://e=2Epearson=2Einfo/pub/cc?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q=
44LOKQGQaQvzbfVXtpKX%3DSRDSCCYD&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq=
6BRYqA77GBUCzgCCzgTVGf6beX6990G11X%3DuHghthxupjHpLkiHgHQJhu=2E=22>Act now=
=2E Early Bird pricing expires on January 13</a>=21 </p>=09
=09
=09
</font></td>
</tr>

<td height=3D=22179=22>
<font size=3D=221=22 face=3D=22arial,helvetica=22>
<hr>
</font>
<table width=3D=22432=22 align=3D=22center=22>
  <tr>
    <td>&nbsp;</td>
    <td width=3D=22250=22 rowspan=3D=224=22 style=3D=22padding-left:1em;=22=
><a rilt=3D=22HTML5Cover=22 href=3D=22http://e=2Epearson=2Einfo/pub/cc?_ri_=
=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q44LOKQGQaQvzbfVXtpKX%3DSRDSCCAR&_=
ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6beX6990G11=
X%3DuHghthxupjHpLkiHgHQJhu=2E=22><img src=3D=22http://ptgmedia=2Epearsoncmg=
=2Ecom/imprint_downloads/informit/images/video/PBMVideoBanner=2Egif=22 alt=
=3D=22Video Tutorials=22 border=3D=220=22 style=3D=22border-width: 0px; bor=
der-style: solid; border-color: =23ccc;=22 /></a></td>
  </tr>
  <tr>
    <td width=3D=22170=22><font size=3D=222=22><img src=3D=22http://ptgmedi=
a=2Epearsoncmg=2Ecom/imprint_downloads/informit/promotions/iPhoneApps/faceb=
ook_32=2Epng=22 style=3D=22float:left; margin: -1px 5px 1px 1px;=22 alt=3D=
=22Facebook=22 /><a style=3D=22color: =23f15a22;=22 rilt=3D=22Facebook=22 h=
ref=3D=22http://e=2Epearson=2Einfo/pub/cc?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQG=
yy4Qisn8Qso3Q44LOKQGQaQvzbfVXtpKX%3DSRDSCCAS&_ei_=3D8312wfG0Xb9X%3DzgDBAB68=
8qzgSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6beX6990G11X%3DuHghthxupjHpLkiHgHQJhu=2E=
=22><font face=3D=22arial,helvetica=22><strong>Like us  on Facebook</strong=
></font></a></font></td>
    </tr>
  <tr>
    <td><font size=3D=222=22><img src=3D=22http://ptgmedia=2Epearsoncmg=2Ec=
om/imprint_downloads/informit/images/twitter_32=2Epng=22 style=3D=22float:l=
eft; margin: -1px 5px 1px 1px;=22 alt=3D=22Twitter=22 /><a style=3D=22color=
: =23f15a22;=22 rilt=3D=22Twitter=22 href=3D=22http://e=2Epearson=2Einfo/pu=
b/cc?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q44LOKQGQaQvzbfVXtpKX%3DS=
RDSCCAT&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6b=
eX6990G11X%3DuHghthxupjHpLkiHgHQJhu=2E=22><font face=3D=22arial,helvetica=
=22><strong>Talk to us on Twitter</strong></font></a></font></td>
  </tr>
 =20
</table>
<font size=3D=221=22 face=3D=22arial,helvetica=22><br />
<p align=3D=22center=22>Pearson Education, 800 East 96th Street, Indianapol=
is, IN  46240<br />
  &copy; All rights reserved=2E<br>
  <a rilt=3D=22Unsubscribe=22 href=3D=22http://e=2Epearson=2Einfo/pub/cc?_r=
i_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q44LOKQGQaQvzbfVXtpKX%3DSRDSCCAU=
&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6BRYqA77GBUCzgCCzgTVGf6beX6990G=
11X%3DuHghthxupjHpLkiHgHQJhu=2E=22>Unsubscribe</a></p>
</font></td>

</tr></table><br>
<br><img border=3D=220=22 width=3D=223=22 height=3D=223=22 src=3D=22http://=
e=2Epearson=2Einfo/pub/as?_ri_=3DX0Gzc2X%3DUQpglLjHJlTQ4rQGyy4Qisn8Qso3Q44L=
OKQGQaQvzbfVXHkMX%3Dw&_ei_=3D8312wfG0Xb9X%3DzgDBAB688qzgSRGqWUWCq6BRYqA77GB=
UCzgCCzgTVGf6beX6990G11X%3DuHghthxupjHpLkiHgHQJhu=2E=22>


</body>
</html>


