function hupa(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',hb='&',r='/',gc='<script defer="defer">hupa.onInjectionDone(\'hupa\')<\/script>',jc='<script id="',A='=',q='?',C='Bad handler "',fc='DOMContentLoaded',Bb="GWT module 'hupa' needs to be (re)compiled, please run a compile or use the Compile/Browse button in hosted mode",o='SCRIPT',lb='Unexpected exception in locale detection, using default: ',kb='_',ib='__gwt_Locale',ic='__gwt_marker_hupa',s='base',nb='begin',cb='bootstrap',cc='cbg_button.css',u='clear.cache.gif',z='content',jb='default',hc='end',ub='gecko',vb='gecko1_8',ec='gwt-dnd.css',yb='gwt.hybrid',Cb='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',bc='head',zb='hosted.html?hupa',ac='href',m='hupa',tb='ie6',sb='ie8',ab='iframe',t='img',bb="javascript:''",Db='link',xb='loadExternalRefs',fb='locale',gb='locale=',v='meta',eb='moduleRequested',dc='moduleStartup',rb='msie',w='name',ob='opera',db='position:absolute;width:0;height:0;border:none',Eb='rel',qb='safari',Ab='selectingPermutation',x='startup',Fb='stylesheet',wb='unknown',mb='user.agent',pb='webkit';var lc=window,k=document,kc=lc.__gwtStatsEvent?function(a){return lc.__gwtStatsEvent(a)}:null,Fc,vc,qc,pc=l,yc={},cd=[],Ec=[],oc=[],Bc,Dc;kc&&kc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!lc.__gwt_stylesLoaded){lc.__gwt_stylesLoaded={}}if(!lc.__gwt_scriptsLoaded){lc.__gwt_scriptsLoaded={}}function uc(){var b=false;try{b=lc.external&&(lc.external.gwtOnLoad&&lc.location.search.indexOf(yb)==-1)}catch(a){}uc=function(){return b};return b}
function xc(){if(Fc&&vc){var c=k.getElementById(m);var b=c.contentWindow;if(uc()){b.__gwt_getProperty=function(a){return rc(a)}}hupa=null;b.gwtOnLoad(Bc,m,pc);kc&&kc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:hc})}}
function sc(){var j,h=ic,i;k.write(jc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){pc=f(j.src)}if(pc==l){var e=k.getElementsByTagName(s);if(e.length>0){pc=e[e.length-1].href}else{pc=f(k.location.href)}}else if(pc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=pc+u;pc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function Cc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}yc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{Dc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{Bc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function nc(a,b){return b in cd[a]}
function mc(a){var b=yc[a];return b==null?null:b}
function rc(d){var e=Ec[d](),b=cd[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Dc){Dc(d,a,e)}throw null}
var tc;function wc(){if(!tc){tc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);kc&&kc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(pc+ad)}}
Ec[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(gb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(hb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=mc(fb)}if(g==null){g=lc[ib]}if(g==null){return jb}while(!nc(fb,g)){var f=g.lastIndexOf(kb);if(f==-1){g=jb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(lb+a);return jb}};cd[fb]={de:0,'default':1,en:2};Ec[mb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(ob)!=-1){return ob}else if(d.indexOf(pb)!=-1){return qb}else if(d.indexOf(rb)!=-1){if(document.documentMode>=8){return sb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return tb}}}}else if(d.indexOf(ub)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return vb}return ub}return wb};cd[mb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};hupa.onScriptLoad=function(){if(tc){vc=true;xc()}};hupa.onInjectionDone=function(){Fc=true;kc&&kc({moduleName:m,subSystem:x,evtGroup:xb,millis:(new Date()).getTime(),type:hc});xc()};sc();var ad;if(uc()){if(lc.external.initModule&&lc.external.initModule(m)){lc.location.reload();return}ad=zb}Cc();kc&&kc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:Ab});if(!ad){try{alert(Bb);return}catch(a){return}}var Ac;function zc(){if(!qc){qc=true;if(!__gwt_stylesLoaded[Cb]){var a=k.createElement(Db);__gwt_stylesLoaded[Cb]=a;a.setAttribute(Eb,Fb);a.setAttribute(ac,pc+Cb);k.getElementsByTagName(bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[cc]){var a=k.createElement(Db);__gwt_stylesLoaded[cc]=a;a.setAttribute(Eb,Fb);a.setAttribute(ac,pc+cc);k.getElementsByTagName(bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[ec]){var a=k.createElement(Db);__gwt_stylesLoaded[ec]=a;a.setAttribute(Eb,Fb);a.setAttribute(ac,pc+ec);k.getElementsByTagName(bc)[0].appendChild(a)}xc();if(k.removeEventListener){k.removeEventListener(fc,zc,false)}if(Ac){clearInterval(Ac)}}}
if(k.addEventListener){k.addEventListener(fc,function(){wc();zc()},false)}var Ac=setInterval(function(){if(/loaded|complete/.test(k.readyState)){wc();zc()}},50);kc&&kc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:hc});kc&&kc({moduleName:m,subSystem:x,evtGroup:xb,millis:(new Date()).getTime(),type:nb});k.write(gc)}
hupa();